version: '2'

services:
  workspace:
    image: busybox:latest
    volumes:
      - ./:/var/www
      - ./containers/nginx/logs:/var/log/nginx
      - ./containers/nginx/sites:/etc/nginx/conf.d
  php-fpm:
    build:
      context: ./containers/php
    ports:
      - 9000
    volumes_from:
      - workspace
    restart: always
  composer:
    build:
      context: ./containers/composer
    volumes:
      - ./:/app
  nginx:
    build:
      context: ./containers/nginx
    volumes_from:
      - workspace
    ports:
      - 8080:80
    depends_on:
      - php-fpm
    restart: always
volumes:
  php-fpm:
    driver: "local"
  nginx:
    driver: "local"
